version: '3'

services:
  app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile-go
    container_name: app
    volumes:
      - .:/go/src
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db
    command: go run main.go
  mysql-db:
    restart: always
    build: 
      context: .
      dockerfile: mysql.Dockerfile
    container_name: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      #MYSQL_ROOT_PASSSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #MYSQL_USER: "root"
      #MYSQL_PASSWORD: "senha"
      MYSQL_DATABASE: "aluguel_veiculo"
    ports:
      - "3305:3306"